parse_config:
    qmk_remove_keycode_prefix:
        - KC_
        - QK_
    qmk_keycode_map:
        XXXXXXX: ""
        "NO": ""
        MINUS: "-"
        MINS: "-"
        EQUAL: "="
        EQL: "="
        LEFT_BRACKET: "["
        LBRC: "["
        RIGHT_BRACKET: "]"
        RBRC: "]"
        BACKSLASH: \
        BSLS: \
        NONUS_HASH: "#"
        NUHS: "#"
        SEMICOLON: ;
        SCLN: ;
        QUOTE: "'"
        QUOT: "'"
        GRAVE: "`"
        GRV: "`"
        COMMA: ","
        COMM: ","
        DOT: .
        SLASH: /
        SLSH: /
        TILDE: "~"
        TILD: "~"
        EXCLAIM: "!"
        EXLM: "!"
        AT: "@"
        HASH: "#"
        DOLLAR: $
        DLR: $
        PERCENT: "%"
        PERC: "%"
        CIRCUMFLEX: ^
        CIRC: ^
        AMPERSAND: "&"
        AMPR: "&"
        ASTERISK: "*"
        ASTR: "*"
        LEFT_PAREN: (
        LPRN: (
        RIGHT_PAREN: )
        RPRN: )
        UNDERSCORE: _
        UNDS: _
        PLUS: +
        LEFT_CURLY_BRACE: "{"
        LCBR: "{"
        RIGHT_CURLY_BRACE: "}"
        RCBR: "}"
        PIPE: "|"
        COLON: ":"
        COLN: ":"
        DOUBLE_QUOTE: '"'
        DQUO: '"'
        DQT: '"'
        LEFT_ANGLE_BRACKET: <
        LABK: <
        LT: <
        RIGHT_ANGLE_BRACKET: ">"
        RABK: ">"
        GT: ">"
        QUESTION: "?"
        QUES: "?"
        HU_0: "0"
        HU_1: "1"
        HU_2: "2"
        HU_3: "3"
        HU_4: "4"
        HU_5: "5"
        HU_6: "6"
        HU_7: "7"
        HU_8: "8"
        HU_9: "9"
        HU_ODIA: "Ö"
        HU_UDIA: "Ü"
        HU_OACU: "Ó"
        HU_Q: "Q"
        HU_W: "W"
        HU_E: "E"
        HU_R: "R"
        HU_T: "T"
        HU_Z: "Z"
        HU_U: "U"
        HU_I: "I"
        HU_O: "O"
        HU_P: "P"
        HU_ODAC: "Ő"
        HU_UACU: "Ú"
        HU_A: "A"
        HU_S: "S"
        HU_D: "D"
        HU_F: "F"
        HU_G: "G"
        HU_H: "H"
        HU_J: "J"
        HU_K: "K"
        HU_L: "L"
        HU_EACU: "É"
        HU_AACU: "Á"
        HU_UDAC: "Ű"
        HU_IACU: "Í"
        HU_Y: "Y"
        HU_X: "X"
        HU_C: "C"
        HU_V: "V"
        HU_B: "B"
        HU_N: "N"
        HU_M: "M"
        HU_COMM: ","
        HU_DOT: "."
        HU_MINS: "-"
        HU_SECT: "§"
        HU_QUOT: "'"
        HU_DQUO: '"'
        HU_PLUS: "+"
        HU_EXLM: "!"
        HU_PERC: "%"
        HU_SLSH: "/"
        HU_EQL: "="
        HU_LPRN: "("
        HU_RPRN: ")"
        HU_QUES: "?"
        HU_COLN: ":"
        HU_UNDS: "_"
        HU_TILD: "~"
        HU_CARN: "ˇ (dead)"
        HU_CIRC: "^ (dead)"
        HU_BREV: "˘ (dead)"
        HU_RNGA: "° (dead)"
        HU_OGON: "˛ (dead)"
        HU_GRV: "`"
        HU_DOTA: "˙ (dead)"
        HU_ACUT: "´ (dead)"
        HU_DACU: "˝ (dead)"
        HU_DIAE: "¨ (dead)"
        HU_CEDL: "¸ (dead)"
        HU_BSLS: "\\"
        HU_PIPE: "|"
        HU_CADI: "Ä"
        HU_EURO: "€"
        HU_DIV: "÷"
        HU_MUL: "×"
        HU_LADI: "ä"
        HU_LDST: "đ"
        HU_CDST: "Đ"
        HU_LBRC: "["
        HU_RBRC: "]"
        HU_LLST: "ł"
        HU_CLST: "Ł"
        HU_DLR: "$"
        HU_SS: "ß"
        HU_CURR: "¤"
        HU_LABK: "<"
        HU_RABK: ">"
        HU_HASH: "#"
        HU_AMPR: "&"
        HU_AT: "@"
        HU_LCBR: "{"
        HU_RCBR: "}"
        HU_SCLN: ";"
        HU_ASTR: "*"
